name: Build Godot Game

on: workflow_call

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main repo
        uses: actions/checkout@v3

      - name: Setup game build folder
        run: mkdir godot-build
        
      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v1
        with:
          version: 4.0.2
          use-dotnet: false # Godot 4 DotNET doesnt have web export yet

      - name: Check Godot Version
        run: godot --version

      - name: Export game
        run: |
          cd src
          godot --headless --export-release DinoGameWeb $GITHUB_WORKSPACE/godot-build/index.html

      - name: Copy licenses
        run: cp -v LICENSE* godot-build

      - name: Upload game artifact
        uses: actions/upload-artifact@v3
        with:
          name: dino-game
          path: godot-build
      
      - name: Run tree
        run: tree