name: Dino Game Build

# on:
#   push:
#     branches:
#       - main
on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v1
        with:
          version: 4.0.2
          use-dotnet: false

      - name: Check Godot Version
        run: godot --version

      - name: Export Game
        run: |
          cd dino-game
          godot --headless --export-release DinoGameWeb